--Spanish translation created by SamuEDL
--Vietnamese translation created by nguyenmao2101
--Italian translation created by theHeroGAC and some strings by Rinnegatamante
--French translation created by Samilop "Cimmerian" Iter
--Turkish translation created by @kemalsanli
--PortugueseBR translation created by @rutantan
--SimplifiedChinese translation created by @Qingyu510
Language = {
    Russian = {
        APP = {
            LIBRARY = "БИБЛИОТЕКА",
            CATALOGS = "КАТАЛОГИ",
            SETTINGS = "НАСТРОЙКИ",
            DOWNLOAD = "ЗАГРУЗКИ",
            HISTORY = "ИСТОРИЯ",
            IMPORT = "ИМПОРТ",
            SEARCH = "Поиск"
        },
        MESSAGE = {
            LOST_CONNECTION = "Соединение потеряно\n\nОжидание подключения...\n\n(Сверните приложение, Зайдите в настройки соединения, нажмите Присоединиться)\n\nНажмите X для отмены всех загрузок и закрытия сообщения\n\nВсе загрузки продолжаться, если соединение восстановится",
            PRESS_TO_UPDATE = "Нажмите X для обновления\nНажмите O для отмены"
        },
        SETTINGS = {
            Language = "Язык",
            ClearChapters = "Очистить сохраненные главы",
            ShowNSFW = "Показывать контент для взрослых",
            ClearLibrary = "Очистить библиотеку",
            ClearCache = "Очистить кэш для неотслеживаемых манг",
            ClearAllCache = "Очистить ВЕСЬ кэш",
            ReaderOrientation = "Ориентация читалки по умолчанию",
            ZoomReader = "Масштабирование страниц манги",
            DoubleTapReader = "Включить двойное нажатие для приближения",
            SwapXO = "Сменить раскладку",
            ShowAuthor = "Разработчик",
            ShowVersion = "Версия",
            CheckUpdate = "Проверить на обновления",
            LatestVersion = "Последняя версия:",
            PleaseWait = "Пожалуйста, подождите",
            FailedToUpdate = "Не получилось обновить приложение",
            NoConnection = "Нет соединения",
            SkipFontLoading = "Пропускать загрузку шрифтов",
            CurrentVersionIs = "Текущая версия:",
            UnzipingVPK = "Извлечение установочного файла",
            ReaderDirection = "Направление чтения манги",
            HideInOffline = "Показывать только загруженные главы в офлайне",
            VersionIsUpToDate = "У вас уже стоит последняя версия",
            Space = "Памяти занято",
            EU = "Европейская",
            JP = "Японская",
            PressAgainToAccept = "Нажмите ещё раз, чтобы подтвердить",
            PressAgainToUpdate = "Нажмите ещё раз, чтобы обновиться до:",
            Reader = "Читалка",
            Controls = "Параметры клавиш",
            Data = "Данные",
            About = "О программе",
            Catalogs = "Каталоги",
            Library = "Библиотека",
            ChangeUI = "Тема",
            PreferredCatalogLanguage = "Предпочитаемый язык",
            LibrarySorting = "Сортировка библиотеки",
            ChapterSorting = "Сортировка глав",
            RefreshLibAtStart = "Обновлять библиотеку при запуске",
            Translators = "Спасибо переводчикам",
            ChangingPageButtons = "Кнопки для смены страницы",
            LeftStickDeadZone = "Мёртвая зона левого джойстика",
            LeftStickSensitivity = "Чувствительность левого джойстика",
            RightStickDeadZone = "Мёртвая зона правого джойстика",
            RightStickSensitivity = "Чувствительность правого джойстика",
            ResetAllSettings = "Сбросить все настройки",
            Other = "Другое",
            SilentDownloads = "Не показывать уведомления связанные с загрузкой",
            Network = "Интернет",
            UseProxy = "Использовать прокси",
            ProxyIP = "IP адрес прокси",
            ProxyPort = "Порт",
            UseProxyAuth = "Аунтентификация прокси",
            ProxyAuth = "логин:пароль",
            SkipCacheChapterChecking = "Пропускать проверки целостности кеша при запуске приложения",
            ConnectionTime = "Время подсоединения к серверу",
            InputValue = "Введите значение",
            OpenInBrowser = "Открыть в браузере",
            SaveDataPath = "Место сохранения данных",
        },
        PAGINGCONTROLS = {
            ["LR"] = "L и R триггеры",
            ["DPAD"] = "Используя крестовину"
        },
        EXTRA = {
            ["DownloadAll"] = "Скачать все главы",
            ["RemoveAll"] = "Удалить все главы",
            ["CancelAll"] = "Отменить загрузку глав",
            ["ClearBookmarks"] = "Очистить закладки",
            ["OpenMangaInBrowser"] = "Открыть мангу в браузере",
        },
        THEME = {
            Dark = "Тёмная",
            Light = "Светлая",
            Blue = "Синяя",
            Crimson = "Малиновый"
        },
        NSFW = {
            [true] = "Показывать",
            [false] = "Не показывать"
        },
        YORN = {
            [true] = "Да",
            [false] = "Нет"
        },
        PARSERS = {
            RUS = "Русский",
            ENG = "Английский",
            ESP = "Испанский",
            PRT = "Португальский",
            FRA = "Французский",
            JAP = "Японский",
            DIF = "Разные",
            TUR = "Турецкий",
            ITA = "Итальянский",
            VIE = "Вьетнамский",
            DEU = "Немецкий",
            BRA = "Бразильский",
            POL = "Польский",
            IDN = "Индонезийский"
        },
        WARNINGS = {
            NO_CHAPTERS = "Главы не найдены"
        },
        READER = {
            PREPARING_PAGES = "Подготовка страниц",
            LOADING_PAGE = "Загрузка страницы",
            LOADING_SEGMENT = "Загрузка сегмента страницы",
            Horizontal = "Горизонтальная",
            Vertical = "Вертикальная",
            Smart = "Умное",
            Height = "По высоте",
            Width = "По ширине",
            LEFT = "Справа налево",
            RIGHT = "Слева направо",
            DOWN = "Сверху вниз",
            Default = "По умолчанию",
        },
        DETAILS = {
            ADD_TO_LIBRARY = "Добавить в библиотеку",
            REMOVE_FROM_LIBRARY = "Удалить из библиотеки",
            PAGE = "Страница : ",
            CONTINUE = "Продолжить",
            START = "Начать чтение",
            DONE = "Прочитано!",
        },
        NOTIFICATIONS = {
            ADDED_TO_LIBRARY = "Добавлено в библиотеку",
            REMOVED_FROM_LIBRARY = "Удалено из библиотеки",
            SEARCHING = 'Поиск "%s"',
            START_DOWNLOAD = "%s: %s\nзагрузка началась!",
            END_DOWNLOAD = "%s: %s\nзагрузка завершена!",
            CANCEL_DOWNLOAD = "%s: %s\nзагрузка прервана!",
            CHAPTER_REMOVE = 'Кэш-глава "%s" удалена!',
            NET_PROBLEM = "Возникли проблемы с интернетом!",
            CHAPTERS_CLEARED = "Сохраненые главы удалены!",
            LIBRARY_CLEARED = "Библиотека очищена!",
            CACHE_CLEARED = "Кэш очищен!",
            DEVELOPER_THING = "Поставь звезду на Github!",
            NEW_UPDATE_AVAILABLE = "Доступно новое обновление",
            NO_SPACE_LEFT = "Недостаточно места",
            REFRESH_COMPLETED = "Обновление выполнено!",
            SETTINGS_RESET = "Настройки были сброшены"
        },
        MODES = {
            Popular = "Популярная",
            Latest = "Последняя",
            Search = "Поиск",
            Alphabet = "Алфавит",
            ByLetter = "По букве",
            ByTag = "По тегу",
        },
        PANEL = {
            BACK = "Назад",
            MODE = "Режим",
            --MODE_POPULAR = "Режим: Популярность",
            --MODE_LATEST = "Режим: Недавнее",
            --MODE_SEARCHING = 'Режим: Поиск "%s"',
            JUMPTOPAGE = "Страница",
            SEARCH = "Поиск",
            SELECT = "Выбрать",
            CHOOSE = "Сменить выделение",
            IMPORT = "Импортировать",
            CHANGE_SECTION = "Сменить меню",
            UPDATE = "Обновить",
            CANCEL = "Отменить",
            DELETE = "Удалить",
            FOLLOW = "Отслеживать",
            UNFOLLOW = "Не отслеживать"
        },
        IMPORT = {
            EXTERNAL_MEMORY = "Внешняя Память",
            DRIVE = "Раздел",
            FOLDER = "Папка",
            GOBACK = "Вернуться",
            FILE = "Файл",
            UNSUPFILE = "Неподдерживаемый файл"
        }
    },
    English = {
        APP = {
            LIBRARY = "LIBRARY",
            CATALOGS = "CATALOGS",
            SETTINGS = "SETTINGS",
            DOWNLOAD = "DOWNLOADS",
            IMPORT = "IMPORT",
            HISTORY = "HISTORY",
            SEARCH = "Search"
        },
        MESSAGE = {
            LOST_CONNECTION = "Connection is lost\n\nWaiting for connection...\n\n(Minimize application, go Wi-Fi Settings and press Connect)\n\nPress X to cancel all downloads and close message\n\nAll downloads will continue if the network is restored",
            PRESS_TO_UPDATE = "Press X to update\nPress O to cancel"
        },
        SETTINGS = {
            Language = "Language",
            ClearChapters = "Clear saved chapters",
            ShowNSFW = "Show NSFW catalogs",
            ClearLibrary = "Clear library",
            ClearCache = "Clear cache of non followed manga",
            ClearAllCache = "Clear all cache",
            ReaderOrientation = "Default reader orientation",
            DoubleTapReader = "Enable double tap zoom",
            ZoomReader = "Reader scaling",
            SwapXO = "Change KeyType",
            ShowAuthor = "Developer",
            ShowVersion = "App version",
            CheckUpdate = "Check for updates",
            SkipFontLoading = "Skip font loading",
            LatestVersion = "Latest version:",
            PleaseWait = "Please wait",
            FailedToUpdate = "Failed to update app",
            NoConnection = "No connection",
            HideInOffline = "Show only downloaded chapters in offline mode",
            UnzipingVPK = "Extracting vpk to install",
            CurrentVersionIs = "Current version is:",
            Space = "Memory used",
            ReaderDirection = "Manga reading direction",
            VersionIsUpToDate = "Your version is up to date",
            EU = "Europe",
            JP = "Japan",
            PressAgainToAccept = "Press again to accept",
            PressAgainToUpdate = "Press again to update on:",
            Reader = "Reader",
            Controls = "Controls Setup",
            Data = "Data settings",
            About = "About program",
            Catalogs = "Catalogs",
            Library = "Library",
            ChangeUI = "Theme",
            PreferredCatalogLanguage = "Preferred Language",
            LibrarySorting = "Library sorting",
            ChapterSorting = "Chapters sorting",
            RefreshLibAtStart = "Refresh library at startup",
            Translators = "Thanks to translators",
            ChangingPageButtons = "Buttons to change page",
            LeftStickDeadZone = "Left stick deadzone",
            LeftStickSensitivity = "Left stick sensitivity",
            RightStickDeadZone = "Right stick deadzone",
            RightStickSensitivity = "Right stick sensitivity",
            ResetAllSettings = "Reset all settings",
            Other = "Other",
            SilentDownloads = "Don't show downloads notifications",
            Network = "Network",
            UseProxy = "Use proxy",
            ProxyIP = "IP address",
            ProxyPort = "Port",
            UseProxyAuth = "Use proxy authentication",
            ProxyAuth = "login:password",
            SkipCacheChapterChecking = "Skip checking cache and saved chapters while loading",
            ConnectionTime = "Connection time for server",
            InputValue = "Input value",
            OpenInBrowser = "Open in browser",
            SaveDataPath = "Save data path",
        },
        PAGINGCONTROLS = {
            ["LR"] = "L and R triggers",
            ["DPAD"] = "Using DPad"
        },
        EXTRA = {
            ["DownloadAll"] = "Download all chapters",
            ["RemoveAll"] = "Remove all chapters",
            ["CancelAll"] = "Cancel downloading chapters",
            ["ClearBookmarks"] = "Clear bookmarks",
            ["OpenMangaInBrowser"] = "Open manga in browser",
        },
        THEME = {
            Dark = "Dark",
            Light = "Light",
            Blue = "Blue",
            Crimson = "Crimson"
        },
        NSFW = {
            [true] = "Show",
            [false] = "Don't show"
        },
        YORN = {
            [true] = "Yes",
            [false] = "No"
        },
        PARSERS = {
            RUS = "Russian",
            ENG = "English",
            ESP = "Spanish",
            PRT = "Portuguese",
            FRA = "French",
            JAP = "Japan",
            DIF = "Different",
            TUR = "Turkish",
            ITA = "Italian",
            VIE = "Vietnamese",
            DEU = "German",
            BRA = "Brazil",
            POL = "Polish",
            IDN = "Indonesian"
        },
        WARNINGS = {
            NO_CHAPTERS = "No chapters"
        },
        READER = {
            PREPARING_PAGES = "Preparing pages",
            LOADING_PAGE = "Loading page",
            LOADING_SEGMENT = "Loading segment",
            Horizontal = "Horizontal",
            Vertical = "Vertical",
            Smart = "Smart",
            Height = "Height",
            Width = "Width",
            LEFT = "Right to left",
            RIGHT = "Left to right",
            DOWN = "Up to down",
            Default = "Default",
        },
        DETAILS = {
            ADD_TO_LIBRARY = "Add to library",
            REMOVE_FROM_LIBRARY = "Remove from library",
            PAGE = "Page : ",
            CONTINUE = "Continue",
            START = "Start reading",
            DONE = "Сompleted!",
        },
        NOTIFICATIONS = {
            ADDED_TO_LIBRARY = "Added to library",
            REMOVED_FROM_LIBRARY = "Removed from library",
            SEARCHING = 'Searching "%s"',
            START_DOWNLOAD = "%s: %s\ndownloading started!",
            END_DOWNLOAD = "%s: %s\nsuccessfuly downloaded!",
            CANCEL_DOWNLOAD = "%s: %s\ndownload is canceled!",
            CHAPTER_REMOVE = "%s deleted!",
            NET_PROBLEM = "There is problems with connection!",
            CHAPTERS_CLEARED = "All saved chapters are cleared!",
            LIBRARY_CLEARED = "Library cleared!",
            CACHE_CLEARED = "Cache has been cleared!",
            DEVELOPER_THING = "Star app on Github!",
            NEW_UPDATE_AVAILABLE = "New update available",
            NO_SPACE_LEFT = "No space left",
            REFRESH_COMPLETED = "Refresh completed!",
            SETTINGS_RESET = "Settings have been reset"
        },
        MODES = {
            Popular = "Popular",
            Latest = "Latest",
            Search = "Search",
            Alphabet = "Alphabet",
            ByLetter = "By Letter",
            ByTag = "By Tag",
        },
        PANEL = {
            BACK = "Back",
            MODE = "Mode",
            --MODE_POPULAR = "Mode: Popular",
            --MODE_LATEST = "Mode: Latest",
            --MODE_SEARCHING = 'Mode: Searching "%s"',
            JUMPTOPAGE = "Jump to page",
            SEARCH = "Search",
            SELECT = "Select",
            CHOOSE = "Choose",
            IMPORT = "Import",
            CHANGE_SECTION = "Change section",
            UPDATE = "Refresh",
            CANCEL = "Cancel",
            DELETE = "Delete",
            FOLLOW = "Follow",
            UNFOLLOW = "Unfollow"
        },
        IMPORT = {
            EXTERNAL_MEMORY = "External Memory",
            DRIVE = "Drive",
            FOLDER = "Folder",
            GOBACK = "Go back",
            FILE = "File",
            UNSUPFILE = "Unsupported file"
        }
    },
    Turkish = {
        APP = {
            LIBRARY = "KÜTÜPHANE",
            CATALOGS = "KATALOG",
            SETTINGS = "SEÇENEKLER",
            DOWNLOAD = "İNDİRİLENLER",
            IMPORT = "İÇE AKTAR",
            HISTORY = "GEÇMİŞ",
            SEARCH = "Ara"
        },
        MESSAGE = {
            LOST_CONNECTION = "Bağlantı kesildi\n\nBağlantı için bekleniyor...\n\n(Uygulamayı küçültün, Wi-Fİ seçeneklerine gidin ve ağa bağlanın)\n\nMesajı kapatmak ve bütün indirmeleri iptal etmek için X e basın\n\nAğa bağlanınca tüm indirmeler devam edecek.",
            PRESS_TO_UPDATE = "Güncellemek için X e basın\nVazgeçmek için O ya basın."
        },
        SETTINGS = {
            Language = "Dil",
            ClearChapters = "Kaydedilen Bölümleri Sil",
            ShowNSFW = "Uygunsuz İçeriği Göster",
            ClearLibrary = "Kütüphaneyi Temizle",
            ClearCache = "Bellekteki Takip Edilmeyen Mangaları Sil",
            ClearAllCache = "Belleği Temizle",
            ReaderOrientation = "Varsayılan Okuyucu Yönü",
            DoubleTapReader = "Çift Tıkla Yakınlaştırmayı Etkinleştir",
            ZoomReader = "Okuyucu Ölçeklendirmesi",
            SwapXO = "Tuş Düzenini Değiştir(X/O)",
            ShowAuthor = "Geliştirici",
            ShowVersion = "Uygulama Sürümü",
            CheckUpdate = "Güncellemeleri Denetle",
            SkipFontLoading = "Font Yüklemesini Atla",
            LatestVersion = "En Son Sürüm:",
            PleaseWait = "Lütfen Bekleyiniz",
            FailedToUpdate = "Uygulamayı Güncelleme Başarısız Oldu",
            NoConnection = "Bağlantı Yok",
            HideInOffline = "Çevrimdışında Sadece İndirilmiş Bölümleri Göster",
            UnzipingVPK = "Vpk Yüklemek İçin Çıkarılıyor",
            CurrentVersionIs = "Mevcut Sürüm:",
            Space = "Kullanılan Hafıza",
            ReaderDirection = "Manga Okuyucu Yönü",
            VersionIsUpToDate = "En Güncel Sürümü Kullanıyorsunuz",
            EU = "Avrupa",
            JP = "Japonya",
            PressAgainToAccept = "Kabul Etmek İçin Tekrar Basın",
            PressAgainToUpdate = "Güncellemek İçin Tekrar Basın:",
            Reader = "Okuyucu",
            Controls = "Kontrol Seçenekleri",
            Data = "Veri Seçenekleri",
            About = "Program Hakkında",
            Catalogs = "Kataloglar",
            Library = "Kütüphane",
            ChangeUI = "Tema",
            PreferredCatalogLanguage = "Tercih Edilen Dil",
            LibrarySorting = "Kütüphane Sıralama",
            ChapterSorting = "Bölüm Sıralama",
            RefreshLibAtStart = "Başlangıçta Kütüphaneyi Yenile",
            Translators = "Çevirmenlere Teşekkürler",
            ChangingPageButtons = "Sayfayı Çevirmeye Yarayan Tuşlar",
            LeftStickDeadZone = "Sol Çubuk Ölü Alanı",
            LeftStickSensitivity = "Sol Çubuk Hassasiyeti",
            RightStickDeadZone = "Sağ Çubuk Ölü Alanı",
            RightStickSensitivity = "Sağ Çubuk Hassasiyeti",
            ResetAllSettings = "Tüm Seçenekleri Sıfırla",
            Other = "Diğer",
            SilentDownloads = "İndirme Bildirimleri Gösterme",
            Network = "Ağ",
            UseProxy = "Proxy Kullan",
            ProxyIP = "IP Adresi",
            ProxyPort = "Port",
            UseProxyAuth = "Proxy Doğrulamayı Kullan",
            ProxyAuth = "GirişBilgisi:Şifre",
            SkipCacheChapterChecking = "Yükleme Ekranında Bellek ve Bölüm Kontrolünü Atla",
            ConnectionTime = "Server'a Bağlanmak İçin Gereken Zaman",
            InputValue = "Giriş Değeri",
            OpenInBrowser = "Tarayıcıda Aç",
            SaveDataPath = "Kaydetme Yolu",
        },
        PAGINGCONTROLS = {
            ["LR"] = "L1 R1 Tuşları",
            ["DPAD"] = "DPAD Tuşları"
        },
        EXTRA = {
            ["DownloadAll"] = "Tüm Bölümleri İndir",
            ["RemoveAll"] = "Tüm Bölümleri Sil",
            ["CancelAll"] = "Bölümleri İndirmeyi İptal Et",
            ["ClearBookmarks"] = "Yer İmlerini Temizle",
            ["OpenMangaInBrowser"] = "Manga'yı Tarayıcıda Aç",
        },
        THEME = {
            Dark = "Karanlık",
            Light = "Aydınlık",
            Blue = "Mavi",
            Crimson = "Kızıl"
        },
        NSFW = {
            [true] = "Göster",
            [false] = "Gösterme"
        },
        YORN = {
            [true] = "Evet",
            [false] = "Hayır"
        },
        PARSERS = {
            RUS = "Rusça",
            ENG = "İnglizce",
            ESP = "İspanyolca",
            PRT = "Portekizce",
            FRA = "Fransızca",
            JAP = "Japonca",
            DIF = "Diğer",
            TUR = "Türkçe",
            ITA = "İtalyanca",
            VIE = "Vietnam Dili",
            DEU = "Almanca",
            BRA = "Brezilya Dili",
            POL = "Lehçe",
            IDN = "Endonezya"
        },
        WARNINGS = {
            NO_CHAPTERS = "Hiç Bölüm Yok"
        },
        READER = {
            PREPARING_PAGES = "Sayfalar Hazırlanıyor",
            LOADING_PAGE = "Sayfalar Yükleniyor",
            LOADING_SEGMENT = "Segment Yükleniyor",
            Horizontal = "Yatay",
            Vertical = "Dikey",
            Smart = "Akıllı Ölçeklendirme",
            Height = "Yüksekliğe Göre",
            Width = "Genişliğe Göre",
            LEFT = "Sola Doğru",
            RIGHT = "Sağa Doğru",
            DOWN = "Aşağı Doğru",
            Default = "Varsayılan",
        },
        DETAILS = {
            ADD_TO_LIBRARY = "Kütüphaneye Ekle",
            REMOVE_FROM_LIBRARY = "Kütüphaneden Sil",
            PAGE = "Sayfa : ",
            CONTINUE = "Devam Et",
            START = "Okumaya Başla",
            DONE = "Tamamlandı!",
        },
        NOTIFICATIONS = {
            ADDED_TO_LIBRARY = "Kütüphaneye Eklendi",
            REMOVED_FROM_LIBRARY = "Kütüphaneden Silindi",
            SEARCHING = '"%s" Aranıyor',
            START_DOWNLOAD = "%s: %s\nİndirme Başladı!",
            END_DOWNLOAD = "%s: %s\nBaşarılı Bir Şekilde İndirildi!",
            CANCEL_DOWNLOAD = "%s: %s\nİndirme İptal Edildi!",
            CHAPTER_REMOVE = "%s Silindi!",
            NET_PROBLEM = "Bağlantıda Sorunlar Var!",
            CHAPTERS_CLEARED = "Tüm Kaydedilmiş Bölümler Temizlendi!",
            LIBRARY_CLEARED = "Kütüphane Temizlendi!",
            CACHE_CLEARED = "Bellek Temizlendi!",
            DEVELOPER_THING = "Github'da Uygulamayı Yıldızlayın!",
            NEW_UPDATE_AVAILABLE = "Yeni Güncelleme Mevcut",
            NO_SPACE_LEFT = "Hafıza Yetersiz",
            REFRESH_COMPLETED = "Yenileme Tamamlandı",
            SETTINGS_RESET = "Seçenekler Sıfırlandı"
        },
        MODES = {
            Popular = "Popüler",
            Latest = "En Yeni",
            Search = "Ara",
            Alphabet = "Alfabetik",
            ByLetter = "Harflerle",
            ByTag = "Tag'a Göre",
        },
        PANEL = {
            BACK = "Geri",
            MODE = "Mod",
            --MODE_POPULAR = "Mod: Önce En Popüler",
            --MODE_LATEST = "Mod: Önce En Yeni",
            --MODE_SEARCHING = 'Mod:"%s" Aranıyor',
            JUMPTOPAGE = "Sayfaya Atla", -- Need to translate
            SEARCH = "Ara",
            SELECT = "Seç",
            CHOOSE = "Seç",
            IMPORT = "İçe Aktar",
            CHANGE_SECTION = "Kategoriyi Değiştir",
            UPDATE = "Yenile",
            CANCEL = "Vazgeç",
            DELETE = "Sil",
            FOLLOW = "Takip Et",
            UNFOLLOW = "Takibi Bırak",
        },
        IMPORT = {
            EXTERNAL_MEMORY = "Taşınabilir Bellek",
            DRIVE = "Cihaz Hafızası",
            FOLDER = "Klasör",
            GOBACK = "Geri Dön",
            FILE = "Dosya",
            UNSUPFILE = "Desteklenmeyen Dosya"
        }
    },
    Vietnamese = {
        APP = {
            LIBRARY = "Thư viện",
            CATALOGS = "Danh mục",
            SETTINGS = "Cài đặt",
            DOWNLOAD = "Tải xuống",
            IMPORT = "Thêm truyện",
            HISTORY = "Lịch sử",
            SEARCH = "Tìm kiếm"
        },
        MESSAGE = {
            LOST_CONNECTION = "Mất kết nối\n\nĐang đợi mạng...\n\n(Hãy chạy ẩn ứng dụng, đi đến cài đặt và tiến hành kết nối mạng)\n\nNhấn X để hủy tất cả tiến trình tải và tắt thông báo\n\nCác tiến trình tải sẽ tự động tiếp tục khi có kết nối mạng",
            PRESS_TO_UPDATE = "Nhấn X để cập nhật\nNhấn O để hủy bỏ"
        },
        SETTINGS = {
            Language = "Ngôn ngữ",
            ClearChapters = "Xóa các tập đã tải",
            ShowNSFW = "Nội dung người lớn",
            ClearLibrary = "Xóa lịch sử",
            ClearCache = "Xóa dữ liệu tạm",
            ClearAllCache = "Xóa tất cả dữ liệu",
            ReaderOrientation = "Trình đọc mặc định",
            ZoomReader = "Thay đổi kích thước",
            DoubleTapReader = "Kích hoạt tính năng chạm hai lần để thu phóng",
            SwapXO = "Chuyển đổi phím chọn",
            ShowAuthor = "Tác giả",
            ShowVersion = "Phiên bản",
            CheckUpdate = "Kiểm tra cập nhật",
            SkipFontLoading = "Bỏ qua tải font chữ",
            LatestVersion = "Phiên bản mới nhất:",
            PleaseWait = "Xin chờ",
            FailedToUpdate = "Không thể cập nhật",
            NoConnection = "Không có kết nối",
            HideInOffline = "Chỉ hiện thị tập đã tải (offline mode)",
            UnzipingVPK = "Giải nén tập tin vpk",
            CurrentVersionIs = "Phiên bản hiện tại:",
            Space = "Bộ nhớ đã dùng",
            ReaderDirection = "Thứ tự khung truyện",
            VersionIsUpToDate = "Đã là phiên bản mới nhất",
            EU = "Europe",
            JP = "Japan",
            PressAgainToAccept = "Bấm lại để xác nhận",
            PressAgainToUpdate = "Bấm lại để cập nhật:",
            Reader = "Trình đọc truyện",
            Controls = "Điều khiển",
            Data = "Bộ nhớ",
            About = "Giới thiệu",
            Catalogs = "Danh mục",
            Library = "Thư viện",
            ChangeUI = "Giao diện",
            PreferredCatalogLanguage = "Ngôn ngữ ưa thích",
            LibrarySorting = "Sắp xếp lại thư viện",
            ChapterSorting = "Sắp xếp lại chương truyện",
            RefreshLibAtStart = "Làm mới thư viện khi khởi động",
            Translators = "Cảm ơn đến các dịch giả",
            ChangingPageButtons = "Nút chuyển trang",
            LeftStickDeadZone = "Deadzone cần điều khiển trái",
            LeftStickSensitivity = "Độ nhạy cần điều khiển trái",
            RightStickDeadZone = "Deadzone cần điều khiển phải",
            RightStickSensitivity = "Độ nhạy cần điều khiển phải",
            ResetAllSettings = "Đặt lại tất cả cài đặt",
            Other = "Khác",
            SilentDownloads = "Không hiển thị thông báo tải xuống",
            Network = "Mạng",
            UseProxy = "Dùng proxy",
            ProxyIP = "Địa chỉ IP",
            ProxyPort = "Cổng",
            UseProxyAuth = "Xác thực proxy",
            ProxyAuth = "tài khoản:mật khẩu",
            SkipCacheChapterChecking = "Bỏ qua kiểm tra bộ nhớ tạm",
            ConnectionTime = "Thời gian kết nối máy chủ",
            InputValue = "Giá trị đầu vào",
            OpenInBrowser = "Mở trong trình duyệt",
            SaveDataPath = "Save data path", --Need to translate
        },
        PAGINGCONTROLS = {
            ["LR"] = "Sử dụng L và R",
            ["DPAD"] = "Sử dụng DPad"
        },
        EXTRA = {
            ["DownloadAll"] = "Tải xuống tất cả chương",
            ["RemoveAll"] = "Xóa tất cả chương",
            ["CancelAll"] = "Hủy bỏ việc tải xuống",
            ["ClearBookmarks"] = "Xóa dấu trang",
            ["OpenMangaInBrowser"] = "Mở truyện trong trình duyệt",
        },
        THEME = {
            Dark = "Tối",
            Light = "Sáng",
            Blue = "Xanh da trời",
            Crimson = "Đỏ thẫm"
        },
        NSFW = {
            [true] = "Hiện",
            [false] = "Ẩn"
        },
        YORN = {
            [true] = "Có",
            [false] = "Không"
        },
        PARSERS = {
            RUS = "Nga",
            ENG = "Anh",
            ESP = "Tây Ban Nha",
            PRT = "Bồ Đào Nha",
            FRA = "Pháp",
            JAP = "Nhật",
            DIF = "Khác",
            TUR = "Thổ Nhĩ Kỳ",
            ITA = "Italia",
            VIE = "Việt Nam",
            DEU = "Tiếng Đức",
            BRA = "Brazil",
            POL = "Ba Lan",
            IDN = "Tiếng Indonesia"
        },
        WARNINGS = {
            NO_CHAPTERS = "Không có tập nào!"
        },
        READER = {
            PREPARING_PAGES = "Đang tải",
            LOADING_PAGE = "Đang tải",
            LOADING_SEGMENT = "Đang tải",
            Horizontal = "Dọc",
            Vertical = "Ngang",
            Smart = "Tự động",
            Height = "Chiều cao",
            Width = "Chiều rộng",
            LEFT = "Phải sang trái",
            RIGHT = "Trái sang phải",
            DOWN = "Trên xuống dưới",
            Default = "Mặc định",
        },
        DETAILS = {
            ADD_TO_LIBRARY = "Thêm vào thư viện",
            REMOVE_FROM_LIBRARY = "Xóa khỏi thư viện",
            PAGE = "Trang : ",
            CONTINUE = "Đọc tiếp",
            START = "Đọc truyện",
            DONE = "Hoàn thành!",
        },
        NOTIFICATIONS = {
            ADDED_TO_LIBRARY = "Đã thêm vào thư viện",
            REMOVED_FROM_LIBRARY = "Đã xóa khỏi thư viện",
            SEARCHING = 'Đang tìm "%s"',
            START_DOWNLOAD = "Bắt đầu tải xuống!\n%s: %s",
            END_DOWNLOAD = "Hoàn thành tải xuống!\n%s: %s",
            CANCEL_DOWNLOAD = "Đã hủy tải xuống!\n%s: %s",
            CHAPTER_REMOVE = "Đã xóa!\n%s",
            NET_PROBLEM = "Lỗi kết nối!",
            CHAPTERS_CLEARED = "Đã xóa tất cả tập đã lưu!",
            LIBRARY_CLEARED = "Đã xóa lịch sử!",
            CACHE_CLEARED = "Đã xóa bộ nhớ tạm!",
            DEVELOPER_THING = "Star app on Github!",
            NEW_UPDATE_AVAILABLE = "Có bản cập nhật mới!",
            NO_SPACE_LEFT = "Không đủ dung lượng lưu trữ!",
            REFRESH_COMPLETED = "Làm mới hoàn tất!",
            SETTINGS_RESET = "Đã đặt lại các cài đặt!"
        },
        MODES = {
            Popular = "Phổ biến",
            Latest = "Mới nhất",
            Search = "Tìm kiếm",
            Alphabet = "Bảng chữ cái",
            ByLetter = "Bằng chữ",
            ByTag = "Bằng nhãn",
        },
        PANEL = {
            BACK = "Trở về",
            MODE = "Chế độ",
            --MODE_POPULAR = "Chế độ: Phổ biến",
            --MODE_LATEST = "Chế độ: Mới nhất",
            --MODE_SEARCHING = 'Chế độ: Tìm kiếm "%s"',
            JUMPTOPAGE = "Đi đến trang",
            SEARCH = "Tìm",
            SELECT = "Chọn",
            CHOOSE = "Điều khiển",
            IMPORT = "Nhập",
            CHANGE_SECTION = "Thay đổi danh mục",
            UPDATE = "Cập nhật",
            CANCEL = "Hủy bỏ",
            DELETE = "Xóa bỏ",
            FOLLOW = "Theo dõi",
            UNFOLLOW = "Bỏ theo dõi",
        },
        IMPORT = {
            EXTERNAL_MEMORY = "External Memory", --Translate please
            DRIVE = "Drive", --Translate please
            FOLDER = "Folder", --Translate please
            GOBACK = "Go back", --Translate please
            FILE = "File", --Translate please
            UNSUPFILE = "Unsupported file" --Translate please
        }
    },
    Spanish = {
        APP = {
            LIBRARY = "LIBRERIA",
            CATALOGS = "CATALOGO",
            SETTINGS = "AJUSTES",
            DOWNLOAD = "DESCARGAS",
            IMPORT = "IMPORTAR",
            HISTORY = "HISTORIAL",
            SEARCH = "Buscar"
        },
        MESSAGE = {
            LOST_CONNECTION = "Se ha perdido la conexión\n\nEsperando conexión...\n\n(Minimiza la app, vete a los ajustes wifi y conectate a tu red wifi)\n\nPresiona X para cancelar todas las descargas y cerrar el mensaje\n\nTodas las descargas continuaran, cuando la conexión sea restaurada.",
            PRESS_TO_UPDATE = "Presiona X para actualizar\nPresiona O para cancelar"
        },
        SETTINGS = {
            Language = "Idioma:",
            ClearChapters = "Eliminar capítulos guardados",
            ShowNSFW = "Mostrar servidores NSFW:",
            ClearLibrary = "Limpiar librería",
            ClearCache = "Eliminar la cache de los mangas que no sigo",
            ClearAllCache = "Eliminar toda la cache",
            ReaderOrientation = "Orientación de lectura:",
            ZoomReader = "Escala de lectura:",
            DoubleTapReader = "Activar doble toque para hacer zoom:",
            SwapXO = "Cambiar KeyType:",
            ShowAuthor = "Autor",
            ShowVersion = "Versión de la APP",
            CheckUpdate = "Buscar actualizaciones",
            SkipFontLoading = "Saltar carga de fuentes:",
            LatestVersion = "Ultima versión:",
            PleaseWait = "Espere, por favor",
            FailedToUpdate = "Fallo la actualización",
            NoConnection = "No hay conexión",
            UnzipingVPK = "Extrayendo vpk para instalar",
            HideInOffline = "Mostrar solo los capítulos descargados en modo offline:",
            Space = "Memoria usada",
            ReaderDirection = "Dirección de lectura:",
            VersionIsUpToDate = "La versión esta al día",
            CurrentVersionIs = "La versión actual es:",
            EU = "Europeo",
            JP = "Japonés",
            PressAgainToAccept = "Presiona renuevo para aceptar.",
            PressAgainToUpdate = "Presiona renuevo para actualizar a:",
            Reader = "Lector",
            Controls = "Controles",
            Data = "Datos",
            About = "Información del programa",
            Catalogs = "Catalogo",
            Library = "Libreria",
            ChangeUI = "Tema:",
            PreferredCatalogLanguage = "Idioma preferido:",
            LibrarySorting = "Organización de librería:",
            ChapterSorting = "Organización de capitulos:",
            RefreshLibAtStart = "Refrescar libreria al iniciar:",
            Translators = "Traductores",
            ChangingPageButtons = "Botones para cambiar de pagina:",
            LeftStickDeadZone = "Zona muerta del jostick izquierdo:",
            LeftStickSensitivity = "Sensibilidad del jostick izquierdo:",
            RightStickDeadZone = "Zona muerta del jostick derecho:",
            RightStickSensitivity = "Sensibilidad del jostick derecho:",
            ResetAllSettings = "Resetear todos los ajustes",
            Other = "Otros",
            SilentDownloads = "No mostrar notificaciones de descargas:",
            Network = "Red",
            UseProxy = "Usar Proxy:",
            ProxyIP = "Dirección IP:",
            ProxyPort = "Puerto:",
            UseProxyAuth = "Usar autenticación proxy:",
            ProxyAuth = "login:contraseña",
            SkipCacheChapterChecking = "Saltar chequeo de cache y capitulos en la pantalla de carga:",
            ConnectionTime = "Tiempo de conexion con el servidor:",
            InputValue = "Introduce un valor",
            OpenInBrowser = "Abrir en navegador",
            SaveDataPath = "Guarda ruta de datos",
        },
        PAGINGCONTROLS = {
            ["LR"] = "Botones L y R",
            ["DPAD"] = "Usar DPad"
        },
        EXTRA = {
            ["DownloadAll"] = "Descargar todos los capítulos",
            ["RemoveAll"] = "Eliminar todos los capítulos",
            ["CancelAll"] = "Cancelar la descarga de los capítulos",
            ["ClearBookmarks"] = "Eliminar marcadores",
            ["OpenMangaInBrowser"] = "Abrir el manga en el navegador",
        },
        THEME = {
            Dark = "Oscuro",
            Light = "Claro",
            Blue = "Azul",
            Crimson = "Carmesí"
        },
        NSFW = {
            [true] = "Mostrar",
            [false] = "No mostrar"
        },
        YORN = {
            [true] = "Si",
            [false] = "No"
        },
        PARSERS = {
            RUS = "Ruso",
            ENG = "Ingles",
            ESP = "Español",
            PRT = "Portugués",
            FRA = "Francés",
            JAP = "Japonés",
            DIF = "Diferentes",
            TUR = "Turco",
            ITA = "Italiano",
            VIE = "Vietnamita",
            DEU = "Aleman",
            BRA = "Brasileño",
            POL = "Polaco",
            IDN = "Indonesia"
        },
        WARNINGS = {
            NO_CHAPTERS = "No hay capítulos"
        },
        READER = {
            PREPARING_PAGES = "Preparando paginas",
            LOADING_PAGE = "Cargando paginas",
            LOADING_SEGMENT = "Cargando segmentos",
            Horizontal = "Horizontal",
            Vertical = "Vertical",
            Smart = "Inteligente",
            Height = "Alto",
            Width = "Ancho",
            LEFT = "Derecha a izquierda",
            RIGHT = "Izquierda a derecha",
            DOWN = "Arriba a abajo",
            Default = "Por defecto",
        },
        DETAILS = {
            ADD_TO_LIBRARY = "Añadir a la libreria",
            REMOVE_FROM_LIBRARY = "Eliminar de la librería",
            PAGE = "Página : ",
            CONTINUE = "Continuar",
            START = "Comenzar lectura",
            DONE = "Сompletado!",
        },
        NOTIFICATIONS = {
            ADDED_TO_LIBRARY = "Añadir a la librería",
            REMOVED_FROM_LIBRARY = "Eliminar de la librería",
            SEARCHING = 'Buscando "%s"',
            START_DOWNLOAD = "%s: %s\nla descargando!",
            END_DOWNLOAD = "%s: %s\ndescargado con éxito!",
            CANCEL_DOWNLOAD = "%s: %s\nla descaga se ha cancelado!",
            CHAPTER_REMOVE = "%s eliminado!",
            NET_PROBLEM = "Hay problemas con la conexion!",
            CHAPTERS_CLEARED = "Todos los capítulos guardados, han sido eliminados!",
            LIBRARY_CLEARED = "La librería ha sido eliminada!",
            CACHE_CLEARED = "La cache ha sido eliminada!",
            DEVELOPER_THING = "Pon una estrella en la app de Github!",
            NEW_UPDATE_AVAILABLE = "Nueva actualización disponible",
            NO_SPACE_LEFT = "No hay espacio",
            REFRESH_COMPLETED = "Refresco completado!",
            SETTINGS_RESET = "Los ajustes han sido resteados"
        },
        MODES = {
            Popular = "Populares",
            Latest = "Ultimos",
            Search = "Buscar",
            Alphabet = "Alfabeticamente",
            ByLetter = "Por letra",
            ByTag = "Por tag",
        },
        PANEL = {
            BACK = "Volver",
            MODE = "Modo",
            --MODE_POPULAR = "Modo: Populares",
            --MODE_LATEST = "Modo: Recientes",
            --MODE_SEARCHING = 'Modo: Buscando "%s"',
            JUMPTOPAGE = "Saltar a la pagina",
            SEARCH = "Buscar",
            SELECT = "Seleccionar",
            CHOOSE = "Escoger",
            IMPORT = "Import",
            CHANGE_SECTION = "Cambiar sección",
            UPDATE = "Actualizar",
            CANCEL = "Cancelar",
            DELETE = "Eliminar",
            FOLLOW = "Seguir",
            UNFOLLOW = "Dejar de seguir",
        },
        IMPORT = {
            EXTERNAL_MEMORY = "Memoria Externa",
            DRIVE = "Drive",
            FOLDER = "Carpeta",
            GOBACK = "Volver",
            FILE = "Archivo",
            UNSUPFILE = "Archivo no soportado"
        }
    },
    Italian = {
        APP = {
            LIBRARY = "LIBRERIA",
            CATALOGS = "CATALOGHI",
            SETTINGS = "IMPOSTAZIONI",
            DOWNLOAD = "DOWNLOADS",
            IMPORT = "IMPORTA",
            HISTORY = "CRONOLOGIA",
            SEARCH = "Ricerca"
        },
        MESSAGE = {
            LOST_CONNECTION = "Connessione persa \n\nIn attesa di connessione ......\n\n(Riduci a icona l'applicazione, vai su Impostazioni Wi-Fi e premi Connetti)\n\nPremi X per annullare tutti i download e chiudere il messaggio \n\nTutti i download continueranno se la rete viene ripristinata",
            PRESS_TO_UPDATE = "Premi X per aggiornare\nPremi O per annullare"
        },
        SETTINGS = {
            Language = "Linguaggio",
            ClearChapters = "Cancella i capitoli salvati",
            ShowNSFW = "Mostra parser NSFW",
            ClearLibrary = "Cancella libreria",
            ClearCache = "Cancella tutta la cache creata per i manga non tracciati",
            ClearAllCache = "Cancella tutta la cache",
            ReaderOrientation = "Orientamento lettore predefinito",
            DoubleTapReader = "Abilita il doppio tocco per ingrandire la funzione",
            ZoomReader = "Ridimensionamento del lettore",
            SwapXO = "Cambia pulsanti X o O",
            ShowAuthor = "Sviluppatore",
            ShowVersion = "Versione APP",
            CheckUpdate = "Controlla gli aggiornamenti",
            SkipFontLoading = "Salta il caricamento del carattere",
            LatestVersion = "Ultima versione:",
            PleaseWait = "Attendere prego",
            FailedToUpdate = "Impossibile aggiornare l'app",
            NoConnection = "Nessuna connessione",
            HideInOffline = "Mostra solo i capitoli scaricati offline",
            UnzipingVPK = "Estrazione del vpk per l' installazione",
            CurrentVersionIs = "La versione attuale è:",
            Space = "Memoria usata",
            ReaderDirection = "Direzione di lettura Manga",
            VersionIsUpToDate = "La tua versione è aggiornata",
            EU = "Europa",
            JP = "Giappone",
            PressAgainToAccept = "Premere di nuovo per accettare",
            PressAgainToUpdate = "Premere di nuovo per aggiornare su:",
            Reader = "Reader",
            Controls = "Impostazioni dei controlli",
            Data = "Impostazioni dei dati",
            About = "A proposito del programma...",
            Catalogs = "Cataloghi",
            Library = "Libreria",
            ChangeUI = "Tema",
            PreferredCatalogLanguage = "Lingua preferita",
            LibrarySorting = "Ordinamento della libreria",
            ChapterSorting = "Ordinamento dei capitoli",
            RefreshLibAtStart = "Aggiorna libreria all'avvio",
            Translators = "Grazie ai traduttori",
            ChangingPageButtons = "Pulsanti per cambiare pagina",
            LeftStickDeadZone = "Deadzone della levetta sinistra",
            LeftStickSensitivity = "Sensibilità levetta sinistra",
            RightStickDeadZone = "Deadzone della levetta destra",
            RightStickSensitivity = "Sensibilità levetta destra",
            ResetAllSettings = "Resetta tutte le impostazioni",
            Other = "Altro",
            SilentDownloads = "Non mostrare le notifiche di download",
            Network = "Rete",
            UseProxy = "Utilizza proxy",
            ProxyIP = "Indirizzo IP",
            ProxyPort = "Porta",
            UseProxyAuth = "Utilizza autenticazione proxy",
            ProxyAuth = "login:password",
            SkipCacheChapterChecking = "Salta controllo della cache e del capitolo nella schermata di caricamento",
            ConnectionTime = "Tempo di connessione per server",
            InputValue = "Valore di Input",
            OpenInBrowser = "Apri nel browser",
            SaveDataPath = "Salva percorso dati",
        },
        PAGINGCONTROLS = {
            ["LR"] = "L e R triggers",
            ["DPAD"] = "Utilizza DPad"
        },
        EXTRA = {
            ["DownloadAll"] = "Scarica tutti i capitoli",
            ["RemoveAll"] = "Rimuovi tutti i capitoli",
            ["CancelAll"] = "Annulla il download dei capitoli",
            ["ClearBookmarks"] = "Cancella segnalibri",
            ["OpenMangaInBrowser"] = "Apri manga nel browser",
        },
        THEME = {
            Dark = "Scuro",
            Light = "Chiaro",
            Blue = "Blu",
            Crimson = "Rosso scuro"
        },
        NSFW = {
            [true] = "Mostra",
            [false] = "Non mostrare"
        },
        YORN = {
            [true] = "Si",
            [false] = "No"
        },
        PARSERS = {
            RUS = "Russo",
            ENG = "Inglese",
            ESP = "Spagnolo",
            PRT = "Portoghese",
            FRA = "Francese",
            JAP = "Giapponese",
            DIF = "Diverso",
            TUR = "Turco",
            ITA = "Italiano",
            VIE = "Vietnamese",
            DEU = "Tedesco",
            BRA = "Brasiliano",
            POL = "Polacco",
            IDN = "Indonesiano"
        },
        WARNINGS = {
            NO_CHAPTERS = "Nessun capitolo"
        },
        READER = {
            PREPARING_PAGES = "Preparazione delle pagine",
            LOADING_PAGE = "Caricamento pagina",
            LOADING_SEGMENT = "Caricamento segmento",
            Horizontal = "Orizzontale",
            Vertical = "Verticale",
            Smart = "Smart",
            Height = "Altezza",
            Width = "Larghezza",
            LEFT = "Da destra a sinistra",
            RIGHT = "Da sinistra a destra",
            DOWN = "Dall'alto verso il basso",
            Default = "Default",
        },
        DETAILS = {
            ADD_TO_LIBRARY = "Aggiungi alla libreria",
            REMOVE_FROM_LIBRARY = "Rimuovi dalla libreria",
            PAGE = "Pagina : ",
            CONTINUE = "Continua",
            START = "Inizia a leggere",
            DONE = "Сompletato!",
        },
        NOTIFICATIONS = {
            ADDED_TO_LIBRARY = "Aggiunto alla libreria",
            REMOVED_FROM_LIBRARY = "Rimosso dalla libreria",
            SEARCHING = 'Ricerca in corso "%s"',
            START_DOWNLOAD = "%s: %s\ndownload avviato!",
            END_DOWNLOAD = "%s: %s\nscaricato con successo!",
            CANCEL_DOWNLOAD = "%s: %s\ndownload è stato cancellato!",
            CHAPTER_REMOVE = "%s cancellato!",
            NET_PROBLEM = "Ci sono problemi con la connessione!",
            CHAPTERS_CLEARED = "Tutti i capitoli salvati vengono cancellati!",
            LIBRARY_CLEARED = "Libreria cancellata!",
            CACHE_CLEARED = "La cache è stata cancellata!",
            DEVELOPER_THING = "dare una stella por lei app su Github!",
            NEW_UPDATE_AVAILABLE = "Nuovo aggiornamento disponibile",
            NO_SPACE_LEFT = "Non è rimasto spazio",
            REFRESH_COMPLETED = "Aggiornamento completato!",
            SETTINGS_RESET = "Le impostazioni sono state ripristinate"
        },
        MODES = {
            Popular = "Popolare",
            Latest = "Più Recente",
            Search = "Cerca",
            Alphabet = "Alfabetico",
            ByLetter = "Per Lettera",
            ByTag = "Per Tag",
        },
        PANEL = {
            BACK = "Indietro",
            MODE = "Modalità",
            --MODE_POPULAR = "Modalità: Popolare",
            --MODE_LATEST = "Modalità: più recente",
            --MODE_SEARCHING = 'Modalità: ricerca "%s"',
            JUMPTOPAGE = "Salta alla pagina",
            SEARCH = "Ricerca",
            SELECT = "Seleziona",
            CHOOSE = "Scegli",
            IMPORT = "Importa",
            CHANGE_SECTION = "Cambia sezione",
            UPDATE = "Aggiorna",
            CANCEL = "Cancella",
            DELETE = "Elimina",
            FOLLOW = "Segui",
            UNFOLLOW = "Smetti di seguire",
        },
        IMPORT = {
            EXTERNAL_MEMORY = "Memoria esterna",
            DRIVE = "Drive",
            FOLDER = "Cartella",
            GOBACK = "Torna Indietro",
            FILE = "File",
            UNSUPFILE = "File non supportato"
        }
    },
    French = {
        APP = {
            LIBRARY = "LIBRAIRIE",
            CATALOGS = "CATALOGUE",
            SETTINGS = "PARAMETRES",
            DOWNLOAD = "TELECHARGEMENT",
            IMPORT = "IMPORTER",
            HISTORY = "HISTORIQUE",
            SEARCH = "Recherche"
        },
        MESSAGE = {
            LOST_CONNECTION = "Connection perdu\n\nEn attente de la reconnection......\n\n(Réduir l'application, aller au paramètres Wi-Fi et appuyez sur connection)\n\nAppuyez sur X pour annuler tout les téléchargments et fermer le message\n\nTout les téléchargements reprondront une fois la connection établie",
            PRESS_TO_UPDATE = "Appuez sur X pour mettre à jour\nAppuyez sur O pour annuler"
        },
        SETTINGS = {
            Language = "Language",
            ClearChapters = "Supprimer les chapitres fini",
            ShowNSFW = "Montrer le NSFW",
            ClearLibrary = "Vider la librairie",
            ClearCache = "Vider le cache des mangas non suivie",
            ClearAllCache = "Vider tout le cache",
            ReaderOrientation = "Orientation du lecteur",
            DoubleTapReader = "Activer le double tap pour zoomer",
            ZoomReader = "Zoom du lecteur",
            SwapXO = "changer entre X ou O",
            ShowAuthor = "Developpeur",
            ShowVersion = "Version de l'app",
            CheckUpdate = "Chercher une mise à jour",
            SkipFontLoading = "Passer le chargement des polices",
            LatestVersion = "Dernière version:",
            PleaseWait = "Veuillez patienter",
            FailedToUpdate = "Impossible de mettre à jour",
            NoConnection = "Pas de connection",
            HideInOffline = "Montrer uniquement les chapitres hors ligne",
            UnzipingVPK = "Extraction du vpk pour l'installation",
            CurrentVersionIs = "Version actuelle:",
            Space = "Mémoire utilisé",
            ReaderDirection = "Sens de lecture",
            VersionIsUpToDate = "La version est la plus récente",
            EU = "Europe",
            JP = "Japonais",
            PressAgainToAccept = "Appuyez encore pour accepter",
            PressAgainToUpdate = "Appuyez encore pour mettre à jour:",
            Reader = "Lecteur",
            Controls = "Paramètre des controles",
            Data = "Paramètre de la date",
            About = "A propos du programme...",
            Catalogs = "Catalogue",
            Library = "Librairie",
            ChangeUI = "Thème",
            PreferredCatalogLanguage = "Langue préféré",
            LibrarySorting = "Ordonner la librairie",
            ChapterSorting = "Ordonner les chapitres",
            RefreshLibAtStart = "Rafraichir la librairie au démarrage",
            Translators = "Merci aux traducteurs",
            ChangingPageButtons = "Bouton pour changer de page",
            LeftStickDeadZone = "Deadzone du joystick gauche",
            LeftStickSensitivity = "Sensibilité du joystick gauche",
            RightStickDeadZone = "Deadzone du joystick droit",
            RightStickSensitivity = "Sensibilité du joystick droit",
            ResetAllSettings = "Restaurer tout les paramètres",
            Other = "Autres",
            SilentDownloads = "Pad de notifications de Téléchargement",
            Network = "Réseau",
            UseProxy = "Utiliser un proxy",
            ProxyIP = "Adresse IP",
            ProxyPort = "Port",
            UseProxyAuth = "Uriliser l'authentification Proxy",
            ProxyAuth = "identifiant:mot de passe",
            SkipCacheChapterChecking = "Passer la vérification du cache et chapitre pendant l'écran de chargement",
            ConnectionTime = "Temps de connection au serveur",
            InputValue = "Insérer une valeur",
            OpenInBrowser = "Ouvrir dans le navigateur",
            SaveDataPath = "Emplacement de la sauvegarde",
        },
        PAGINGCONTROLS = {
            ["LR"] = "Boutons L et R",
            ["DPAD"] = "Utiliser le Dpad"
        },
        EXTRA = {
            ["DownloadAll"] = "Télécharger tout les chapitres",
            ["RemoveAll"] = "Retirer tout les chapitres",
            ["CancelAll"] = "Annuler le téléchargement des chapitres",
            ["ClearBookmarks"] = "Vider les marques pages",
            ["OpenMangaInBrowser"] = "Ouvrir le manga dans le navigateur",
        },
        THEME = {
            Dark = "Sombre",
            Light = "Lumineux",
            Blue = "Bleu",
            Crimson = "Rouge foncé"
        },
        NSFW = {
            [true] = "Montrer",
            [false] = "Ne pas montrer"
        },
        YORN = {
            [true] = "Oui",
            [false] = "Non"
        },
        PARSERS = {
            RUS = "Russe",
            ENG = "Anglais",
            ESP = "Espagnol",
            PRT = "Portugais",
            FRA = "Français",
            JAP = "Japonais",
            DIF = "Divers",
            TUR = "Turque",
            ITA = "Italien",
            VIE = "Vietnamien",
            DEU = "Allemand",
            BRA = "Brésilien",
            POL = "Polonais",
            IDN = "Indonésien"
        },
        WARNINGS = {
            NO_CHAPTERS = "Pas de chapitres"
        },
        READER = {
            PREPARING_PAGES = "Préparation des pages",
            LOADING_PAGE = "Chargement de la page",
            LOADING_SEGMENT = "Chargement par parties",
            Horizontal = "Horizontale",
            Vertical = "Verticale",
            Smart = "Adapté",
            Height = "Hauteur",
            Width = "Longueur",
            LEFT = "Droite à gauche",
            RIGHT = "Gauche à droite",
            DOWN = "Haut en bas",
            Default = "Défaut",
        },
        DETAILS = {
            ADD_TO_LIBRARY = "Ajouter à la librairie",
            REMOVE_FROM_LIBRARY = "Enlever de la librairie",
            PAGE = "Page : ",
            CONTINUE = "Continuer",
            START = "Commencer à lire",
            DONE = "Terminé!",
        },
        NOTIFICATIONS = {
            ADDED_TO_LIBRARY = "Ajouté à la librairie",
            REMOVED_FROM_LIBRARY = "Retiré de la librairie",
            SEARCHING = 'En train de rechercher "%s"',
            START_DOWNLOAD = "%s: %s\nle téléchargement a débuté!",
            END_DOWNLOAD = "%s: %s\ntéléchargement complété!",
            CANCEL_DOWNLOAD = "%s: %s\nle téléchargement a été annulé!",
            CHAPTER_REMOVE = "%s supprimé!",
            NET_PROBLEM = "Un problème réseau est survenu.",
            CHAPTERS_CLEARED = "Les chapitres ont été vidé!",
            LIBRARY_CLEARED = "La librairie a été vidé!",
            CACHE_CLEARED = "Le cache a été vidé!",
            DEVELOPER_THING = "Donner une étoile a l'app sur github!",
            NEW_UPDATE_AVAILABLE = "Nouvelle mise à jour disponible",
            NO_SPACE_LEFT = "Plus d'espace disponible",
            REFRESH_COMPLETED = "Mise à jour complète!",
            SETTINGS_RESET = "Les paramètres vont être restauré"
        },
        MODES = {
            Popular = "Populaire",
            Latest = "Nouveau",
            Search = "Chercher",
            Alphabet = "Alphabet",
            ByLetter = "Par lettre",
            ByTag = "Par Tag",
        },
        PANEL = {
            BACK = "Retourner",
            MODE = "Mode",
            --MODE_POPULAR = "Mode: populaire",
            --MODE_LATEST = "Mode: plus récent",
            --MODE_SEARCHING = 'Mode: recherche "%s"',
            JUMPTOPAGE = "Sauter à la page",
            SEARCH = "Rechercher",
            SELECT = "Sélectionner",
            CHOOSE = "Choisir",
            IMPORT = "Importer",
            CHANGE_SECTION = "Changer de section",
            UPDATE = "Mettre à jour",
            CANCEL = "Annuler",
            DELETE = "Supprimer",
            FOLLOW = "Suivre",
            UNFOLLOW = "Ne plus suivre",
        },
        IMPORT = {
            EXTERNAL_MEMORY = "Mémoire Externe",
            DRIVE = "Disque",
            FOLDER = "Dossier",
            GOBACK = "Retour",
            FILE = "Fichier",
            UNSUPFILE = "Fichier non supporté"
        }
    },
    PortugueseBR = {
        APP = {
            LIBRARY = "BIBLIOTECA",
            CATALOGS = "CATÁLOGOS",
            SETTINGS = "CONFIGURAÇÕES",
            DOWNLOAD = "DOWNLOADS",
            IMPORT = "IMPORTAR",
            HISTORY = "HISTÓRICO",
            SEARCH = "Pesquisa"
        },
        MESSAGE = {
            LOST_CONNECTION = "Conexão foi perdida\n\nEsperando por conexão...\n\n(Minimize a aplicação, vá para as configurações do Wi-Fi e pressione Conectar)\n\nAperte X para cancelar todos os downloads e fechar a mensagem\n\nTodos os downloads vão continuar se a conexão for restaurada",
            PRESS_TO_UPDATE = "Aperte X para atualizar\nAperte O para cancelar"
        },
        SETTINGS = {
            Language = "Idioma",
            ClearChapters = "Limpar capítulos salvos",
            ShowNSFW = "Mostrar sites NSFW",
            ClearLibrary = "Limpar biblioteca",
            ClearCache = "Limpar cache de mangas não seguidos",
            ClearAllCache = "Limpar todo cache",
            ReaderOrientation = "Orientação padrão do leitor",
            DoubleTapReader = "Habilitar toque duplo para zoom",
            ZoomReader = "Escala do leitor",
            SwapXO = "Mudar tipo de tecla",
            ShowAuthor = "Desenvolvedor",
            ShowVersion = "Versão do programa",
            CheckUpdate = "Verificar por atualizações",
            SkipFontLoading = "Pular carregamento de fontes",
            LatestVersion = "Última versão:",
            PleaseWait = "Por favor aguarde",
            FailedToUpdate = "Falha ao atualizar o aplicativo",
            NoConnection = "Sem conexão",
            HideInOffline = "Mostrar apenas capítulos baixados no modo offline",
            UnzipingVPK = "Extraindo vpk para instalar",
            CurrentVersionIs = "Versão atual:",
            Space = "Memória usada",
            ReaderDirection = "Direção de leitura do manga",
            VersionIsUpToDate = "Sua versão está atualizada",
            EU = "Europa",
            JP = "Japão",
            PressAgainToAccept = "Pressione novamente para aceitar",
            PressAgainToUpdate = "Pressione novamente para atualizar:",
            Reader = "Leitor",
            Controls = "Configuração de controle",
            Data = "Configurações de dados",
            About = "Sobre o programa",
            Catalogs = "Catálogos",
            Library = "Biblioteca",
            ChangeUI = "Tema",
            PreferredCatalogLanguage = "Idioma preferido",
            LibrarySorting = "Ordenação da biblioteca",
            ChapterSorting = "Ordenação dos capítulos",
            RefreshLibAtStart = "Atualizar biblioteca ao iniciar",
            Translators = "Agradecimentos aos tradutores",
            ChangingPageButtons = "Botões para mudar página",
            LeftStickDeadZone = "Zona morta do analógico esquerdo",
            LeftStickSensitivity = "Sensibilidade do analógico esquerdo",
            RightStickDeadZone = "Zona morta do analógico direito",
            RightStickSensitivity = "Sensibilidade do analógico direito",
            ResetAllSettings = "Resetar todas as configurações",
            Other = "Outros",
            SilentDownloads = "Não exibir notificações de downloads",
            Network = "Rede",
            UseProxy = "Usar proxy",
            ProxyIP = "Endereço IP",
            ProxyPort = "Porta",
            UseProxyAuth = "Usar autenticação de proxy",
            ProxyAuth = "usuário:senha",
            SkipCacheChapterChecking = "Pular verificação de cache e capítulo na tela de carregamento",
            ConnectionTime = "Tempo de conexão com o servidor",
            InputValue = "Insira um valor",
            OpenInBrowser = "Abrir no navegador",
            SaveDataPath = "Salvar caminho dos dados",
        },
        PAGINGCONTROLS = {
            ["LR"] = "Botões L e R",
            ["DPAD"] = "Usando DPad"
        },
        EXTRA = {
            ["DownloadAll"] = "Baixar todos os capítulos",
            ["RemoveAll"] = "Remover todos os capítulos",
            ["CancelAll"] = "Cancelar download de capítulos",
            ["ClearBookmarks"] = "Limpar marcadores de página",
            ["OpenMangaInBrowser"] = "Abrir manga no navegador",
        },
        THEME = {
            Dark = "Escuro",
            Light = "Claro",
            Blue = "Azul",
            Crimson = "Carmesin"
        },
        NSFW = {
            [true] = "Exibir",
            [false] = "Não exibir"
        },
        YORN = {
            [true] = "Sim",
            [false] = "Não"
        },
        PARSERS = {
            RUS = "Russo",
            ENG = "Inglês",
            ESP = "Espanhol",
            PRT = "Português",
            FRA = "Francês",
            JAP = "Japonês",
            DIF = "Diferente",
            TUR = "Turco",
            ITA = "Italiano",
            VIE = "Vietnamita",
            DEU = "Alemão",
            BRA = "Português-Brasil",
            POL = "Polonês",
            IDN = "Indonésien"
        },
        WARNINGS = {
            NO_CHAPTERS = "Sem capítulos"
        },
        READER = {
            PREPARING_PAGES = "Preparando páginas",
            LOADING_PAGE = "Carregando página",
            LOADING_SEGMENT = "Carregando segmento",
            Horizontal = "Horizontal",
            Vertical = "Vertical",
            Smart = "Inteligente",
            Height = "Altura",
            Width = "Largura",
            LEFT = "Direita para a esquerda",
            RIGHT = "Esquerda para a direita",
            DOWN = "Cima para baixo",
            Default = "Padrão",
        },
        DETAILS = {
            ADD_TO_LIBRARY = "Adicionar a biblioteca",
            REMOVE_FROM_LIBRARY = "Remover da biblioteca",
            PAGE = "Página : ",
            CONTINUE = "Continuar",
            START = "Começar leitura",
            DONE = "Completado!",
        },
        NOTIFICATIONS = {
            ADDED_TO_LIBRARY = "Adicionado a biblioteca",
            REMOVED_FROM_LIBRARY = "Removido da biblioteca",
            SEARCHING = 'Pesquisando "%s"',
            START_DOWNLOAD = "%s: %s\ndownload iniciado!",
            END_DOWNLOAD = "%s: %s\ndownload completado!",
            CANCEL_DOWNLOAD = "%s: %s\ndownload foi cancelado!",
            CHAPTER_REMOVE = "%s deletado!",
            NET_PROBLEM = "Existem problemas com a conexão!",
            CHAPTERS_CLEARED = "Todos os capítulos salvos foram apagados!",
            LIBRARY_CLEARED = "Biblioteca foi apagada!",
            CACHE_CLEARED = "Cache foi limpo!",
            DEVELOPER_THING = "Dar uma estrela ao programa no Github!",
            NEW_UPDATE_AVAILABLE = "Nova atualização disponível",
            NO_SPACE_LEFT = "Sem espaço",
            REFRESH_COMPLETED = "Atualização completada!",
            SETTINGS_RESET = "Configurações foram resetadas"
        },
        MODES = {
            Popular = "Popular",
            Latest = "Últimos",
            Search = "Pesquisar",
            Alphabet = "Alfabeto",
            ByLetter = "Por letra",
            ByTag = "Por marcador",
        },
        PANEL = {
            BACK = "Voltar",
            MODE = "Modo:",
            --[[
            MODE_POPULAR = "Modo: Popular",
            MODE_LATEST = "Modo: Últimos",
            MODE_SEARCHING = 'Modo: Pesquisando "%s"',
            ]]
            JUMPTOPAGE = "Ir para página",
            SEARCH = "Pesquisar",
            SELECT = "Selecionar",
            CHOOSE = "Escolher",
            IMPORT = "Importar",
            CHANGE_SECTION = "Mudar seção",
            UPDATE = "Atualizar",
            CANCEL = "Cancelar",
            DELETE = "Deletar",
            FOLLOW = "Seguir",
            UNFOLLOW = "Parar de seguir",
        },
        IMPORT = {
            EXTERNAL_MEMORY = "Memória externa",
            DRIVE = "Disco",
            FOLDER = "Pasta",
            GOBACK = "Voltar",
            FILE = "Arquivo",
            UNSUPFILE = "Arquivo não suportado"
        }
    },
    SimplifiedChinese = {
        APP = {
            LIBRARY = "书架", 
            CATALOGS = "目录", 
            SETTINGS = "设置", 
            DOWNLOAD = "下载", 
            IMPORT = "导入", 
            HISTORY = "历史", 
            SEARCH = "搜索" 
        },
        MESSAGE = {
            LOST_CONNECTION = "连接丢失\n\n等待连接...\n\n(Minimize applica设置WIFI设置,然后按连接键)\n\n按x取消所有下载和close message\n\n如果网络恢复正常,所有下载将继续", 
            PRESS_TO_UPDATE = "按×更新\n按○取消" 
        },
        SETTINGS = {
            Language = "语言", 
            ClearChapters = "清除已保存的章节", 
            ShowNSFW = "显示成人内容", 
            ClearLibrary = "清除书架", 
            ClearCache = "清除未导入的缓存", 
            ClearAllCache = "清除所有缓存", 
            ReaderOrientation = "屏幕方向",
            DoubleTapReader = "启用双击缩放", 
            ZoomReader = "页面缩放",
            SwapXO = "变更按键类型", 
            ShowAuthor = "开发者", 
            ShowVersion = "应用程序版本", 
            CheckUpdate = "检查更新", 
            SkipFontLoading = "跳过字体加载", 
            LatestVersion = "最新版本:",
            PleaseWait = "请稍候", 
            FailedToUpdate = "app更新失败", 
            NoConnection = "没有连接", 
            HideInOffline = "仅在离线模式下显示下载的章节", 
            UnzipingVPK = "解压vpk安装", 
            CurrentVersionIs = "当前版本:",
            Space = "已用内存", 
            ReaderDirection = "阅读方向",
            VersionIsUpToDate = "已是最新版本", 
            EU = "欧洲", 
            JP = "日本", 
            PressAgainToAccept = "再次确认操作", 
            PressAgainToUpdate = "再次确认更新:",
            Reader = "阅读",
            Controls = "控制器", 
            Data = "数据", 
            About = "关于", 
            Catalogs = "目录", 
            Library = "书架", 
            ChangeUI = "主题", 
            PreferredCatalogLanguage = "首选语言", 
            LibrarySorting = "书架排序",
            ChapterSorting = "漫画章节排序", 
            RefreshLibAtStart = "在启动时刷新库", 
            Translators = "感谢以下翻译人员", 
            ChangingPageButtons = "变更页面按钮", 
            LeftStickDeadZone = "左摇杆死区", 
            LeftStickSensitivity = "左摇杆灵敏度", 
            RightStickDeadZone = "右摇杆死区", 
            RightStickSensitivity = "右摇杆灵敏度", 
            ResetAllSettings = "重置所有设置", 
            Other = "其他",
            SilentDownloads = "不显示下载通知",
            Network = "网络",
            UseProxy = "使用代理", 
            ProxyIP = "IP 地址", 
            ProxyPort = "端口", 
            UseProxyAuth = "使用代理认证", 
            ProxyAuth = "验证密码", 
            SkipCacheChapterChecking = "跳过验证缓存和保存文件", 
            ConnectionTime = "服务器连接时间", 
            InputValue = "输入值", 
            OpenInBrowser = "在浏览器打开", 
            SaveDataPath = "储存路径", 
        },
        PAGINGCONTROLS = {
            ["LR"] = "L和R按键", 
            ["DPAD"] = "使用DPad" 
        },
        EXTRA = {
            ["DownloadAll"] = "下载所有章节", 
            ["RemoveAll"] = "删除所有章节", 
            ["CancelAll"] = "取消下载章节", 
            ["ClearBookmarks"] = "删除书签", 
            ["OpenMangaInBrowser"] = "用浏览器打开漫画", 
        },
        THEME = {
            Dark = "星空黑", 
            Light = "简洁白", 
            Blue = "尼罗蓝", 
            Crimson = "朱砂红" 
        },
        NSFW = {
            [true] = "显示", 
            [false] = "不显示" 
        },
        YORN = {
            [true] = "是", 
            [false] = "否" 
        },
        PARSERS = {
            RUS = "俄国",
            ENG = "英国", 
            ESP = "西班牙",
            PRT = "葡萄牙",
            FRA = "法国",
            JAP = "日本",
            DIF = "全语言",
            TUR = "土耳其",
            ITA = "意大利",
            VIE = "越南",
            DEU = "德国",
            BRA = "巴西",
            POL = "波兰",
            IDN = "印度尼西亚"
        },
        WARNINGS = {
            NO_CHAPTERS = "没有章节" 
        },
        READER = {
            PREPARING_PAGES = "准备页面", 
            LOADING_PAGE = "加载页面", 
            LOADING_SEGMENT = "加载阶段", 
            Horizontal = "竖屏",
            Vertical = "横屏",
            Smart = "适应屏幕",
            Height = "匹配高度",
            Width = "匹配宽度",
            LEFT = "从右到左", 
            RIGHT = "从左到右", 
            DOWN = "从上到下", 
            Default = "默认", 
        },
        DETAILS = {
            ADD_TO_LIBRARY = "添加到书架", 
            REMOVE_FROM_LIBRARY = "从书架中删除", 
            PAGE = "当前页:",

            CONTINUE = "继续阅读", 
            START = "开始阅读", 
            DONE = "已看完", 

       },
        NOTIFICATIONS = {
            ADDED_TO_LIBRARY = "已添加到书架", 
            REMOVED_FROM_LIBRARY = "从书架中已删除", 
            SEARCHING = '正在搜索 "%s"', 
            START_DOWNLOAD = "%s: %s\n开始下载!",
            END_DOWNLOAD = "%s: %s\n下载成功!",  
            CANCEL_DOWNLOAD = "%s: %s\n下载已取消", 
            CHAPTER_REMOVE = "%s 删除", 
            NET_PROBLEM = "连接出现错误", 
            CHAPTERS_CLEARED = "已清除已保存的章节!", 
            LIBRARY_CLEARED = "书架已清除!", 
            CACHE_CLEARED = "缓存已被清除!",
            DEVELOPER_THING = "Star app on Github!",
            NEW_UPDATE_AVAILABLE = "发现新版本",
            NO_SPACE_LEFT = "没有剩余空间",
            REFRESH_COMPLETED = "刷新完成!",
            SETTINGS_RESET = "设置已重置"
        },
        MODES = {
            Popular = "热门",
            Latest = "最新",
            Search = "搜索",
            Alphabet = "字母",
            ByLetter = "按信息",
            ByTag = "按标签",
        },
        PANEL = {
            BACK = "返回",
            MODE = "模式",
            --MODE_POPULAR = "模式：热门",
            --MODE_LATEST = "模式：最新",
            --MODE_SEARCHING = '模式：搜索 "%s"',
            JUMPTOPAGE = "跳转到页面",
            SEARCH = "搜索",
            SELECT = "确认",
            CHOOSE = "选择",
            IMPORT = "导入",
            CHANGE_SECTION = "变更页面",
            UPDATE = "刷新",
            CANCEL = "取消",
            DELETE = "删除",
            FOLLOW = "关注",
            UNFOLLOW = "取消关注"
        },
        IMPORT = {
            EXTERNAL_MEMORY = "外部内存", 
            DRIVE = "驱动",
            FOLDER = "文件夹", 
            GOBACK = "返回", 
            FILE = "文件",
            UNSUPFILE = "不支持文件" 
        }
    }
}

LanguageNames = {
    Russian = {
        Russian = "Русский",
        English = "Английский",
        Turkish = "Турецкий",
        Spanish = "Испанский",
        Vietnamese = "Вьетнамский",
        French = "Французский",
        Italian = "Итальянский",
        PortugueseBR = "Бразильский португальский",
        SimplifiedChinese = "Упрощенный китайский",
        Default = "Системный"
    },
    English = {
        Russian = "Russian",
        English = "English",
        Turkish = "Turkish",
        Spanish = "Spanish",
        Vietnamese = "Vietnamese",
        French = "French",
        Italian = "Italian",
        PortugueseBR = "Brazilian portuguese",
        SimplifiedChinese = "Simplified Chinese",
        Default = "System"
    },
    Turkish = {
        Russian = "Rusça",
        English = "İngilizce",
        Turkish = "Türkçe",
        Spanish = "İspanyolca",
        Vietnamese = "Vietnam Dili",
        French = "Fransızca",
        Italian = "İtalyanca",
        PortugueseBR = "Brezilya Portekizcesi",
        SimplifiedChinese = "Basitleştirilmiş Çince",
        Default = "Sistem Dili"
    },
    Spanish = {
        Russian = "Ruso",
        English = "Ingles",
        Turkish = "Turco",
        Spanish = "Español",
        Vietnamese = "Vietnamita",
        French = "Francés",
        Italian = "Italiano",
        PortugueseBR = "Portugués Brasileño",
        SimplifiedChinese = "Chino simplificado",
        Default = "Sistema"
    },
    Vietnamese = {
        Russian = "Tiếng Nga",
        English = "Tiếng Anh",
        Turkish = "Thổ Nhĩ Kỳ",
        Spanish = "Tiếng Tây Ban Nha",
        Italian = "Italia",
        French = "PhápF",
        Vietnamese = "Tiếng Việt",
        PortugueseBR = "Tiếng Bồ Đào Nha của người brazi",
        SimplifiedChinese = "Tiếng Trung giản thể",
        Default = "Hệ thống"
    },
    Italian = {
        Russian = "Russo",
        English = "Inglese",
        Turkish = "Turco",
        Spanish = "Spagnolo",
        Italian = "Italiano",
        French = "Francese",
        Vietnamese = "Vietnamese",
        PortugueseBR = "Portoghese Brasiliano",
        SimplifiedChinese = "Cinese semplificato",
        Default = "Sistema"
    },
    French = {
        Russian = "Russe",
        English = "Anglais",
        Turkish = "Turque",
        Spanish = "Espagnol",
        Italian = "Italien",
        French = "Français",
        Vietnamese = "Vietnamien",
        PortugueseBR = "Portugais brésilien",
        SimplifiedChinese = "Chinois simplifié",
        Default = "Système"
    },
    PortugueseBR = {
        Russian = "Russo",
        English = "Inglês",
        Turkish = "Turco",
        Spanish = "Espanhol",
        Italian = "Italiano",
        French = "Francês",
        Vietnamese = "Vietnamita",
        PortugueseBR = "Português Brasileiro",
        SimplifiedChinese = "Chinês simplificado",
        Default = "Sistema"
    },
    SimplifiedChinese = {
        Russian = "俄语",
        English = "英语",
        Turkish = "土耳其语",
        Spanish = "西班牙语",
        Vietnamese = "越南语",
        French = "法语",
        Italian = "意大利语",
        PortugueseBR = "巴西葡萄牙语",
        SimplifiedChinese = "简体中文",
        Default = "默认"
    }
}

local language_now = System.getLanguage()
if language_now == 8 then
    Language.Default = Language.Russian
    LanguageNames.Default = LanguageNames.Russian
elseif language_now == 3 then
    Language.Default = Language.Spanish
    LanguageNames.Default = LanguageNames.Spanish
elseif language_now == 19 then
    Language.Default = Language.Turkish
    LanguageNames.Default = LanguageNames.Turkish
elseif language_now == 5 then
    Language.Default = Language.Italian
    LanguageNames.Default = LanguageNames.Italian
elseif language_now == 2 then
    Language.Default = Language.French
    LanguageNames.Default = LanguageNames.French
elseif language_now == 17 then
    Language.Default = Language.PortugueseBR
    LanguageNames.Default = LanguageNames.PortugueseBR
elseif language_now == 11 then
    Language.Default = Language.SimplifiedChinese
    LanguageNames.Default = LanguageNames.SimplifiedChinese
else
    Language.Default = Language.English
    LanguageNames.Default = LanguageNames.English
end
local langs = {}
for k, _ in pairs(Language) do
    langs[#langs + 1] = k
end
function GetLanguages()
    return langs
end
